[workspace]
# Conventional PR title
release_pr_name = "chore(release): release ${version}"
# Conventional branch name
branch = "chore/release-plz"
# Always keep changelog updated
changelog_update = true
# Release type
release_type = "prod"
